name: LuckySky-Opalium
main: de.opalium.luckysky.LuckySkyPlugin
version: ${version}
api-version: "1.21"
author: DemusOpalium
description: ${description}

commands:
  ls:
    description: LuckySky Verwaltungsbefehle
    usage: /ls <start|stop|reset|clean|plat|plat+|corridor|sign|bind|mode5|mode20|mode60|wither|taunt_on|taunt_off>
    permission: luckysky.admin
    aliases: [luckysky]

permissions:
  luckysky.admin:
    description: Zugriff auf alle LuckySky Verwaltungsbefehle
    default: op
