name: LuckySky
main: de.opalium.luckysky.LuckySkyPlugin
version: 0.1.0
api-version: '1.21'
author: DemusOpalium
softdepend: [Multiverse-Core, PlaceholderAPI, Essentials, ProtocolLib]
commands:
  ls:
    description: LuckySky Admin
    usage: /ls help
    permission: luckysky.admin
permissions:
  luckysky.admin:
    default: op
