name: LuckySky
main: de.opalium.luckysky.LuckySkyPlugin
version: 1.2.0
api-version: '1.21'
author: DemusOpalium
softdepend: [Multiverse-Core, PlaceholderAPI, Essentials, ProtocolLib]
commands:
  ls:
    description: LuckySky base command
    usage: /ls <reload|duels>
    permission: opalium.luckysky.base
  arena:
    description: Manage the LuckySky arena runtime
    usage: /arena
    permission: opalium.luckysky.arena
  duelsui:
    description: Opens the LuckySky duels interface
    usage: /duelsui
    permission: opalium.luckysky.duels.mod
permissions:
  opalium.luckysky.base:
    description: Allows using the /luckysky command
    default: true
  opalium.luckysky.admin:
    description: Allows administrative LuckySky actions such as /ls reload
    default: op
    children:
      opalium.luckysky.base: true
  opalium.luckysky.arena:
    description: Allows managing the LuckySky arena runtime via /arena
    default: op
    children:
      opalium.luckysky.base: true
  opalium.luckysky.duels.use:
    description: Allows /ls duels to interact with LuckySky duels
    default: true
    children:
      opalium.luckysky.base: true
  opalium.luckysky.duels.mod:
    description: Allows moderating LuckySky duels with /duelsui
    default: op
    children:
      opalium.luckysky.duels.use: true
